"""
Client Configuration Helper
Chạy script này trên máy CLIENT để tự động config
"""

import os
import sys

def setup_client_config():
    """Setup cấu hình cho client"""
    
    print("\n" + "="*70)
    print(" "*20 + "CLIENT CONFIGURATION HELPER")
    print("="*70 + "\n")
    
    # Nhập Server IP
    print("Step 1: Enter Server Information")
    print("-" * 70)
    server_ip = input("Enter SERVER IP address (e.g., 192.168.1.10): ").strip()
    
    if not server_ip:
        print("Server IP is required!")
        return
    
    # Validate IP format (simple)
    parts = server_ip.split('.')
    if len(parts) != 4:
        print("Invalid IP format! Should be like: 192.168.1.10")
        return
    
    print(f"\nServer IP set to: {server_ip}")
    
    # Tạo config file
    config_content = f"""# Client Configuration
# Generated by client_config.py

SERVER_IP = "{server_ip}"

# Service Ports
HTTP_PORT = 8000
TCP_PORT = 9000
TCP_SSL_PORT = 9001
GRPC_PORT = 50051
MULTICAST_GROUP = "224.1.1.1"
MULTICAST_PORT = 5007

# URLs
HTTP_API_URL = f"http://{{SERVER_IP}}:{{HTTP_PORT}}"
HTTP_DOCS_URL = f"http://{{SERVER_IP}}:{{HTTP_PORT}}/docs"

# Connection strings
def get_tcp_config(use_ssl=False):
    return {{
        'host': SERVER_IP,
        'port': TCP_SSL_PORT if use_ssl else TCP_PORT,
        'use_ssl': use_ssl
    }}

def get_grpc_config():
    return {{
        'host': SERVER_IP,
        'port': GRPC_PORT
    }}

def get_multicast_config():
    return {{
        'group': MULTICAST_GROUP,
        'port': MULTICAST_PORT
    }}

# Display info
def show_connection_info():
    print("\\n" + "="*70)
    print("Connection Information")
    print("="*70)
    print(f"Server IP: {{SERVER_IP}}")
    print(f"\\nWeb Browser: {{HTTP_DOCS_URL}}")
    print(f"TCP Transfer: {{SERVER_IP}}:{{TCP_PORT}}")
    print(f"gRPC Search: {{SERVER_IP}}:{{GRPC_PORT}}")
    print("="*70 + "\\n")

if __name__ == "__main__":
    show_connection_info()
"""
    
    # Lưu file
    config_file = "client/client_config.py"
    os.makedirs("client", exist_ok=True)
    
    with open(config_file, 'w', encoding='utf-8') as f:
        f.write(config_content)
    
    print(f"\nConfiguration saved to: {config_file}")
    
    # Hiển thị next steps
    print("\n" + "="*70)
    print("NEXT STEPS")
    print("="*70)
    print()
    print("1. Test connection:")
    print(f"   - Open browser: http://{server_ip}:8000/docs")
    print(f"   - Try ping: ping {server_ip}")
    print()
    print("2. Use TCP Client:")
    print("   python client/tcp_client.py")
    print(f"   (Will auto-connect to {server_ip}:9000)")
    print()
    print("3. Use gRPC Client:")
    print("   python client/grpc_client.py")
    print(f"   (Will auto-connect to {server_ip}:50051)")
    print()
    print("4. Listen to Multicast:")
    print("   python client/multicast_client.py")
    print()
    
    # Test connection
    print("="*70)
    print("CONNECTION TEST")
    print("="*70)
    print()
    
    import socket
    
    # Test ping
    print(f"Testing connection to {server_ip}...")
    try:
        socket.setdefaulttimeout(2)
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        
        # Test HTTP port
        result = s.connect_ex((server_ip, 8000))
        if result == 0:
            print(f"HTTP port 8000: Open")
        else:
            print(f"HTTP port 8000: Closed (Server may not be running)")
        s.close()
        
        # Test TCP port
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = s.connect_ex((server_ip, 9000))
        if result == 0:
            print(f"TCP port 9000: Open")
        else:
            print(f"TCP port 9000: Closed")
        s.close()
        
    except Exception as e:
        print(f"Connection test failed: {e}")
        print(f"\nPossible issues:")
        print(f"1. Server is not running")
        print(f"2. Firewall is blocking connections")
        print(f"3. Wrong IP address")
        print(f"4. Not in the same network")
    
    print("\n" + "="*70)
    print("Client configuration completed!")
    print("="*70 + "\n")

if __name__ == "__main__":
    try:
        setup_client_config()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user")
    except Exception as e:
        print(f"\n\nError: {e}")