# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.grpc_files import file_search_pb2 as app_dot_grpc__files_dot_file__search__pb2


class FileSearchServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchFiles = channel.unary_unary(
                '/filesearch.FileSearchService/SearchFiles',
                request_serializer=app_dot_grpc__files_dot_file__search__pb2.SearchRequest.SerializeToString,
                response_deserializer=app_dot_grpc__files_dot_file__search__pb2.SearchResponse.FromString,
                )
        self.GetFileInfo = channel.unary_unary(
                '/filesearch.FileSearchService/GetFileInfo',
                request_serializer=app_dot_grpc__files_dot_file__search__pb2.FileRequest.SerializeToString,
                response_deserializer=app_dot_grpc__files_dot_file__search__pb2.FileInfo.FromString,
                )
        self.ListAllFiles = channel.unary_unary(
                '/filesearch.FileSearchService/ListAllFiles',
                request_serializer=app_dot_grpc__files_dot_file__search__pb2.Empty.SerializeToString,
                response_deserializer=app_dot_grpc__files_dot_file__search__pb2.FileList.FromString,
                )


class FileSearchServiceServicer(object):
    """Service definition
    """

    def SearchFiles(self, request, context):
        """Tìm kiếm file theo keyword
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileInfo(self, request, context):
        """Lấy thông tin chi tiết file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllFiles(self, request, context):
        """Lấy danh sách tất cả file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFiles,
                    request_deserializer=app_dot_grpc__files_dot_file__search__pb2.SearchRequest.FromString,
                    response_serializer=app_dot_grpc__files_dot_file__search__pb2.SearchResponse.SerializeToString,
            ),
            'GetFileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileInfo,
                    request_deserializer=app_dot_grpc__files_dot_file__search__pb2.FileRequest.FromString,
                    response_serializer=app_dot_grpc__files_dot_file__search__pb2.FileInfo.SerializeToString,
            ),
            'ListAllFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllFiles,
                    request_deserializer=app_dot_grpc__files_dot_file__search__pb2.Empty.FromString,
                    response_serializer=app_dot_grpc__files_dot_file__search__pb2.FileList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filesearch.FileSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileSearchService(object):
    """Service definition
    """

    @staticmethod
    def SearchFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/filesearch.FileSearchService/SearchFiles',
            app_dot_grpc__files_dot_file__search__pb2.SearchRequest.SerializeToString,
            app_dot_grpc__files_dot_file__search__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/filesearch.FileSearchService/GetFileInfo',
            app_dot_grpc__files_dot_file__search__pb2.FileRequest.SerializeToString,
            app_dot_grpc__files_dot_file__search__pb2.FileInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAllFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/filesearch.FileSearchService/ListAllFiles',
            app_dot_grpc__files_dot_file__search__pb2.Empty.SerializeToString,
            app_dot_grpc__files_dot_file__search__pb2.FileList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
