# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/grpc_files/file_search.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n app/grpc_files/file_search.proto\x12\nfilesearch\"/\n\rSearchRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"J\n\x0eSearchResponse\x12#\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x14.filesearch.FileInfo\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"\x1e\n\x0b\x46ileRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x05\"\xe8\x01\n\x08\x46ileInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x19\n\x11original_filename\x18\x03 \x01(\t\x12\x11\n\tfile_size\x18\x04 \x01(\x03\x12\x11\n\tfile_type\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x11\n\tis_public\x18\x07 \x01(\x08\x12\x16\n\x0e\x64ownload_count\x18\x08 \x01(\x05\x12\x13\n\x0buploaded_at\x18\t \x01(\t\x12\x10\n\x08owner_id\x18\n \x01(\x05\x12\x16\n\x0eowner_username\x18\x0b \x01(\t\"D\n\x08\x46ileList\x12#\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x14.filesearch.FileInfo\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2\xd0\x01\n\x11\x46ileSearchService\x12\x44\n\x0bSearchFiles\x12\x19.filesearch.SearchRequest\x1a\x1a.filesearch.SearchResponse\x12<\n\x0bGetFileInfo\x12\x17.filesearch.FileRequest\x1a\x14.filesearch.FileInfo\x12\x37\n\x0cListAllFiles\x12\x11.filesearch.Empty\x1a\x14.filesearch.FileListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc_files.file_search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHREQUEST']._serialized_start=48
  _globals['_SEARCHREQUEST']._serialized_end=95
  _globals['_SEARCHRESPONSE']._serialized_start=97
  _globals['_SEARCHRESPONSE']._serialized_end=171
  _globals['_FILEREQUEST']._serialized_start=173
  _globals['_FILEREQUEST']._serialized_end=203
  _globals['_FILEINFO']._serialized_start=206
  _globals['_FILEINFO']._serialized_end=438
  _globals['_FILELIST']._serialized_start=440
  _globals['_FILELIST']._serialized_end=508
  _globals['_EMPTY']._serialized_start=510
  _globals['_EMPTY']._serialized_end=517
  _globals['_FILESEARCHSERVICE']._serialized_start=520
  _globals['_FILESEARCHSERVICE']._serialized_end=728
# @@protoc_insertion_point(module_scope)
